Addition of additional scripts argument to test_options
pmcharrison/psychTestR pull request #94
Opened 2021-12-01 15:26 UTC by syntheso

Addition of feature to allow users to include additional scripts via test_options, as discussed in #93.

2021-12-01 16:03 UTC, pmcharrison requested changes

2021-12-01 16:03 UTC, pmcharrison commented on R/options.R
> +                         additional_scripts = NULL) {
I suggest replacing `NULL` with `character()`

2021-12-01 16:03 UTC, pmcharrison commented on R/ui.R
>      "js/navigate-away.js"
Instead of the code below, you can just put `opt$additional_scripts` inside the first definition of `scripts`, and `c()` should do the job for you.

2021-12-01 16:03 UTC, pmcharrison commented on R/options.R
> +#' A character vector of any additional scripts to include.
Explain that these are meant to be file paths.

2021-12-01 16:03 UTC, pmcharrison commented on R/options.R
> +#' @param additional_scripts
Documentation needs to be rebuilt to update the corresponding `Rd` file

2021-12-01 17:21 UTC, syntheso commented
Requested changes made.

2021-12-02 10:34 UTC, syntheso commented
Hm, I don't get these most recent errors when I check() locally.

2022-06-20 14:20 UTC, pmcharrison commented
> Sure, I'll work on that now.
> 
> Out of interest, why keep includeScript for the native psychTestR scripts? I know they're pretty small and so don't degrade performance, but if they too used normal script tags, everything could be kept in one function.

Hi @sebsilas, the reason is that to use script tags psychTestR would have to take control of the user's `www` directory, to make sure that those scripts were always present on launch. We could do this but it's a bit invasive and requires a bit of coding overhead.

2022-06-20 14:41 UTC, sebsilas commented
> > Sure, I'll work on that now.
> > Out of interest, why keep includeScript for the native psychTestR scripts? I know they're pretty small and so don't degrade performance, but if they too used normal script tags, everything could be kept in one function.
> 
> Hi @sebsilas, the reason is that to use script tags psychTestR would have to take control of the user's `www` directory, to make sure that those scripts were always present on launch. We could do this but it's a bit invasive and requires a bit of coding overhead.

I think you already responded to this somewhere else.

The commit I would like you to pull is 80416abc5bcc2591126f197b2a10071248be01c5. It wasn't what you previously suggested (2 separate arguments for different kinds of scripts), but has worked well for me. I can't remember exactly what now, but I ran into several issues with the separate argument approach and this heuristic works, at least for my use case.

2022-06-20 15:38 UTC, pmcharrison commented
Thanks @sebsilas, the commit looks good to me. The way the process ordinarily works is that you create a pull request containing the changes you want to merge. Seems like the present pull request contains some other changes too?

2023-03-29 09:15 UTC, closed without merging